language: r

matrix:
  include:
   - os: linux
   - os: osx

install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi
  - cd $TRAVIS_BUILD_DIR
  - eval "$(gimme 1.11)"

script:
  - make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
