# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1exploreraddressStatus Class
#'
#' @field unconfirmed 
#' @field block_seq 
#' @field label 
#' @field confirmed 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1exploreraddressStatus <- R6::R6Class(
  'Apiv1exploreraddressStatus',
  public = list(
    `unconfirmed` = NULL,
    `block_seq` = NULL,
    `label` = NULL,
    `confirmed` = NULL,
    initialize = function(`unconfirmed`, `block_seq`, `label`, `confirmed`){
      if (!missing(`unconfirmed`)) {
        self$`unconfirmed` <- `unconfirmed`
      }
      if (!missing(`block_seq`)) {
        stopifnot(is.numeric(`block_seq`), length(`block_seq`) == 1)
        self$`block_seq` <- `block_seq`
      }
      if (!missing(`label`)) {
        stopifnot(is.numeric(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`confirmed`)) {
        self$`confirmed` <- `confirmed`
      }
    },
    toJSON = function() {
      Apiv1exploreraddressStatusObject <- list()
      if (!is.null(self$`unconfirmed`)) {
        Apiv1exploreraddressStatusObject[['unconfirmed']] <- self$`unconfirmed`
      }
      if (!is.null(self$`block_seq`)) {
        Apiv1exploreraddressStatusObject[['block_seq']] <- self$`block_seq`
      }
      if (!is.null(self$`label`)) {
        Apiv1exploreraddressStatusObject[['label']] <- self$`label`
      }
      if (!is.null(self$`confirmed`)) {
        Apiv1exploreraddressStatusObject[['confirmed']] <- self$`confirmed`
      }

      Apiv1exploreraddressStatusObject
    },
    fromJSON = function(Apiv1exploreraddressStatusJson) {
      Apiv1exploreraddressStatusObject <- jsonlite::fromJSON(Apiv1exploreraddressStatusJson)
      if (!is.null(Apiv1exploreraddressStatusObject$`unconfirmed`)) {
        self$`unconfirmed` <- Apiv1exploreraddressStatusObject$`unconfirmed`
      }
      if (!is.null(Apiv1exploreraddressStatusObject$`block_seq`)) {
        self$`block_seq` <- Apiv1exploreraddressStatusObject$`block_seq`
      }
      if (!is.null(Apiv1exploreraddressStatusObject$`label`)) {
        self$`label` <- Apiv1exploreraddressStatusObject$`label`
      }
      if (!is.null(Apiv1exploreraddressStatusObject$`confirmed`)) {
        self$`confirmed` <- Apiv1exploreraddressStatusObject$`confirmed`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "unconfirmed": %s,
           "block_seq": %d,
           "label": %d,
           "confirmed": %s
        }',
        self$`unconfirmed`,
        self$`block_seq`,
        self$`label`,
        self$`confirmed`
      )
    },
    fromJSONString = function(Apiv1exploreraddressStatusJson) {
      Apiv1exploreraddressStatusObject <- jsonlite::fromJSON(Apiv1exploreraddressStatusJson)
      self$`unconfirmed` <- Apiv1exploreraddressStatusObject$`unconfirmed`
      self$`block_seq` <- Apiv1exploreraddressStatusObject$`block_seq`
      self$`label` <- Apiv1exploreraddressStatusObject$`label`
      self$`confirmed` <- Apiv1exploreraddressStatusObject$`confirmed`
    }
  )
)
