# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1pendingTxsTransaction Class
#'
#' @field outputs 
#' @field inner_hash 
#' @field inputs 
#' @field sigs 
#' @field length 
#' @field txid 
#' @field type 
#' @field timestamp 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1pendingTxsTransaction <- R6::R6Class(
  'Apiv1pendingTxsTransaction',
  public = list(
    `outputs` = NULL,
    `inner_hash` = NULL,
    `inputs` = NULL,
    `sigs` = NULL,
    `length` = NULL,
    `txid` = NULL,
    `type` = NULL,
    `timestamp` = NULL,
    initialize = function(`outputs`, `inner_hash`, `inputs`, `sigs`, `length`, `txid`, `type`, `timestamp`){
      if (!missing(`outputs`)) {
        stopifnot(is.list(`outputs`), length(`outputs`) != 0)
        lapply(`outputs`, function(x) stopifnot(R6::is.R6(x)))
        self$`outputs` <- `outputs`
      }
      if (!missing(`inner_hash`)) {
        stopifnot(is.character(`inner_hash`), length(`inner_hash`) == 1)
        self$`inner_hash` <- `inner_hash`
      }
      if (!missing(`inputs`)) {
        stopifnot(is.list(`inputs`), length(`inputs`) != 0)
        lapply(`inputs`, function(x) stopifnot(is.character(x)))
        self$`inputs` <- `inputs`
      }
      if (!missing(`sigs`)) {
        stopifnot(is.list(`sigs`), length(`sigs`) != 0)
        lapply(`sigs`, function(x) stopifnot(is.character(x)))
        self$`sigs` <- `sigs`
      }
      if (!missing(`length`)) {
        stopifnot(is.numeric(`length`), length(`length`) == 1)
        self$`length` <- `length`
      }
      if (!missing(`txid`)) {
        stopifnot(is.character(`txid`), length(`txid`) == 1)
        self$`txid` <- `txid`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
    },
    toJSON = function() {
      Apiv1pendingTxsTransactionObject <- list()
      if (!is.null(self$`outputs`)) {
        Apiv1pendingTxsTransactionObject[['outputs']] <- lapply(self$`outputs`, function(x) x$toJSON())
      }
      if (!is.null(self$`inner_hash`)) {
        Apiv1pendingTxsTransactionObject[['inner_hash']] <- self$`inner_hash`
      }
      if (!is.null(self$`inputs`)) {
        Apiv1pendingTxsTransactionObject[['inputs']] <- self$`inputs`
      }
      if (!is.null(self$`sigs`)) {
        Apiv1pendingTxsTransactionObject[['sigs']] <- self$`sigs`
      }
      if (!is.null(self$`length`)) {
        Apiv1pendingTxsTransactionObject[['length']] <- self$`length`
      }
      if (!is.null(self$`txid`)) {
        Apiv1pendingTxsTransactionObject[['txid']] <- self$`txid`
      }
      if (!is.null(self$`type`)) {
        Apiv1pendingTxsTransactionObject[['type']] <- self$`type`
      }
      if (!is.null(self$`timestamp`)) {
        Apiv1pendingTxsTransactionObject[['timestamp']] <- self$`timestamp`
      }

      Apiv1pendingTxsTransactionObject
    },
    fromJSON = function(Apiv1pendingTxsTransactionJson) {
      Apiv1pendingTxsTransactionObject <- jsonlite::fromJSON(Apiv1pendingTxsTransactionJson)
      if (!is.null(Apiv1pendingTxsTransactionObject$`outputs`)) {
        self$`outputs` <- lapply(Apiv1pendingTxsTransactionObject$`outputs`, function(x) {
          outputsObject <- Apiv1exploreraddressOutputs$new()
          outputsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          outputsObject
        })
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`inner_hash`)) {
        self$`inner_hash` <- Apiv1pendingTxsTransactionObject$`inner_hash`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`inputs`)) {
        self$`inputs` <- Apiv1pendingTxsTransactionObject$`inputs`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`sigs`)) {
        self$`sigs` <- Apiv1pendingTxsTransactionObject$`sigs`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`length`)) {
        self$`length` <- Apiv1pendingTxsTransactionObject$`length`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`txid`)) {
        self$`txid` <- Apiv1pendingTxsTransactionObject$`txid`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`type`)) {
        self$`type` <- Apiv1pendingTxsTransactionObject$`type`
      }
      if (!is.null(Apiv1pendingTxsTransactionObject$`timestamp`)) {
        self$`timestamp` <- Apiv1pendingTxsTransactionObject$`timestamp`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "outputs": [%s],
           "inner_hash": %s,
           "inputs": [%s],
           "sigs": [%s],
           "length": %d,
           "txid": %s,
           "type": %d,
           "timestamp": %d
        }',
        lapply(self$`outputs`, function(x) paste(x$toJSON(), sep=",")),
        self$`inner_hash`,
        lapply(self$`inputs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`sigs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`length`,
        self$`txid`,
        self$`type`,
        self$`timestamp`
      )
    },
    fromJSONString = function(Apiv1pendingTxsTransactionJson) {
      Apiv1pendingTxsTransactionObject <- jsonlite::fromJSON(Apiv1pendingTxsTransactionJson)
      self$`outputs` <- lapply(Apiv1pendingTxsTransactionObject$`outputs`, function(x) Apiv1exploreraddressOutputs$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`inner_hash` <- Apiv1pendingTxsTransactionObject$`inner_hash`
      self$`inputs` <- Apiv1pendingTxsTransactionObject$`inputs`
      self$`sigs` <- Apiv1pendingTxsTransactionObject$`sigs`
      self$`length` <- Apiv1pendingTxsTransactionObject$`length`
      self$`txid` <- Apiv1pendingTxsTransactionObject$`txid`
      self$`type` <- Apiv1pendingTxsTransactionObject$`type`
      self$`timestamp` <- Apiv1pendingTxsTransactionObject$`timestamp`
    }
  )
)
