# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1walletsMeta Class
#'
#' @field filename 
#' @field encrypted 
#' @field crypto_type 
#' @field label 
#' @field type 
#' @field version 
#' @field coin 
#' @field timestamp 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1walletsMeta <- R6::R6Class(
  'Apiv1walletsMeta',
  public = list(
    `filename` = NULL,
    `encrypted` = NULL,
    `crypto_type` = NULL,
    `label` = NULL,
    `type` = NULL,
    `version` = NULL,
    `coin` = NULL,
    `timestamp` = NULL,
    initialize = function(`filename`, `encrypted`, `crypto_type`, `label`, `type`, `version`, `coin`, `timestamp`){
      if (!missing(`filename`)) {
        stopifnot(is.character(`filename`), length(`filename`) == 1)
        self$`filename` <- `filename`
      }
      if (!missing(`encrypted`)) {
        self$`encrypted` <- `encrypted`
      }
      if (!missing(`crypto_type`)) {
        stopifnot(is.character(`crypto_type`), length(`crypto_type`) == 1)
        self$`crypto_type` <- `crypto_type`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`coin`)) {
        stopifnot(is.character(`coin`), length(`coin`) == 1)
        self$`coin` <- `coin`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
    },
    toJSON = function() {
      Apiv1walletsMetaObject <- list()
      if (!is.null(self$`filename`)) {
        Apiv1walletsMetaObject[['filename']] <- self$`filename`
      }
      if (!is.null(self$`encrypted`)) {
        Apiv1walletsMetaObject[['encrypted']] <- self$`encrypted`
      }
      if (!is.null(self$`crypto_type`)) {
        Apiv1walletsMetaObject[['crypto_type']] <- self$`crypto_type`
      }
      if (!is.null(self$`label`)) {
        Apiv1walletsMetaObject[['label']] <- self$`label`
      }
      if (!is.null(self$`type`)) {
        Apiv1walletsMetaObject[['type']] <- self$`type`
      }
      if (!is.null(self$`version`)) {
        Apiv1walletsMetaObject[['version']] <- self$`version`
      }
      if (!is.null(self$`coin`)) {
        Apiv1walletsMetaObject[['coin']] <- self$`coin`
      }
      if (!is.null(self$`timestamp`)) {
        Apiv1walletsMetaObject[['timestamp']] <- self$`timestamp`
      }

      Apiv1walletsMetaObject
    },
    fromJSON = function(Apiv1walletsMetaJson) {
      Apiv1walletsMetaObject <- jsonlite::fromJSON(Apiv1walletsMetaJson)
      if (!is.null(Apiv1walletsMetaObject$`filename`)) {
        self$`filename` <- Apiv1walletsMetaObject$`filename`
      }
      if (!is.null(Apiv1walletsMetaObject$`encrypted`)) {
        self$`encrypted` <- Apiv1walletsMetaObject$`encrypted`
      }
      if (!is.null(Apiv1walletsMetaObject$`crypto_type`)) {
        self$`crypto_type` <- Apiv1walletsMetaObject$`crypto_type`
      }
      if (!is.null(Apiv1walletsMetaObject$`label`)) {
        self$`label` <- Apiv1walletsMetaObject$`label`
      }
      if (!is.null(Apiv1walletsMetaObject$`type`)) {
        self$`type` <- Apiv1walletsMetaObject$`type`
      }
      if (!is.null(Apiv1walletsMetaObject$`version`)) {
        self$`version` <- Apiv1walletsMetaObject$`version`
      }
      if (!is.null(Apiv1walletsMetaObject$`coin`)) {
        self$`coin` <- Apiv1walletsMetaObject$`coin`
      }
      if (!is.null(Apiv1walletsMetaObject$`timestamp`)) {
        self$`timestamp` <- Apiv1walletsMetaObject$`timestamp`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filename": %s,
           "encrypted": %s,
           "crypto_type": %s,
           "label": %s,
           "type": %s,
           "version": %s,
           "coin": %s,
           "timestamp": %d
        }',
        self$`filename`,
        self$`encrypted`,
        self$`crypto_type`,
        self$`label`,
        self$`type`,
        self$`version`,
        self$`coin`,
        self$`timestamp`
      )
    },
    fromJSONString = function(Apiv1walletsMetaJson) {
      Apiv1walletsMetaObject <- jsonlite::fromJSON(Apiv1walletsMetaJson)
      self$`filename` <- Apiv1walletsMetaObject$`filename`
      self$`encrypted` <- Apiv1walletsMetaObject$`encrypted`
      self$`crypto_type` <- Apiv1walletsMetaObject$`crypto_type`
      self$`label` <- Apiv1walletsMetaObject$`label`
      self$`type` <- Apiv1walletsMetaObject$`type`
      self$`version` <- Apiv1walletsMetaObject$`version`
      self$`coin` <- Apiv1walletsMetaObject$`coin`
      self$`timestamp` <- Apiv1walletsMetaObject$`timestamp`
    }
  )
)
