# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1exploreraddressOutputs Class
#'
#' @field hours 
#' @field dst 
#' @field coins 
#' @field uxid 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1exploreraddressOutputs <- R6::R6Class(
  'Apiv1exploreraddressOutputs',
  public = list(
    `hours` = NULL,
    `dst` = NULL,
    `coins` = NULL,
    `uxid` = NULL,
    initialize = function(`hours`, `dst`, `coins`, `uxid`){
      if (!missing(`hours`)) {
        stopifnot(is.numeric(`hours`), length(`hours`) == 1)
        self$`hours` <- `hours`
      }
      if (!missing(`dst`)) {
        stopifnot(is.character(`dst`), length(`dst`) == 1)
        self$`dst` <- `dst`
      }
      if (!missing(`coins`)) {
        stopifnot(is.character(`coins`), length(`coins`) == 1)
        self$`coins` <- `coins`
      }
      if (!missing(`uxid`)) {
        stopifnot(is.character(`uxid`), length(`uxid`) == 1)
        self$`uxid` <- `uxid`
      }
    },
    toJSON = function() {
      Apiv1exploreraddressOutputsObject <- list()
      if (!is.null(self$`hours`)) {
        Apiv1exploreraddressOutputsObject[['hours']] <- self$`hours`
      }
      if (!is.null(self$`dst`)) {
        Apiv1exploreraddressOutputsObject[['dst']] <- self$`dst`
      }
      if (!is.null(self$`coins`)) {
        Apiv1exploreraddressOutputsObject[['coins']] <- self$`coins`
      }
      if (!is.null(self$`uxid`)) {
        Apiv1exploreraddressOutputsObject[['uxid']] <- self$`uxid`
      }

      Apiv1exploreraddressOutputsObject
    },
    fromJSON = function(Apiv1exploreraddressOutputsJson) {
      Apiv1exploreraddressOutputsObject <- jsonlite::fromJSON(Apiv1exploreraddressOutputsJson)
      if (!is.null(Apiv1exploreraddressOutputsObject$`hours`)) {
        self$`hours` <- Apiv1exploreraddressOutputsObject$`hours`
      }
      if (!is.null(Apiv1exploreraddressOutputsObject$`dst`)) {
        self$`dst` <- Apiv1exploreraddressOutputsObject$`dst`
      }
      if (!is.null(Apiv1exploreraddressOutputsObject$`coins`)) {
        self$`coins` <- Apiv1exploreraddressOutputsObject$`coins`
      }
      if (!is.null(Apiv1exploreraddressOutputsObject$`uxid`)) {
        self$`uxid` <- Apiv1exploreraddressOutputsObject$`uxid`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hours": %d,
           "dst": %s,
           "coins": %s,
           "uxid": %s
        }',
        self$`hours`,
        self$`dst`,
        self$`coins`,
        self$`uxid`
      )
    },
    fromJSONString = function(Apiv1exploreraddressOutputsJson) {
      Apiv1exploreraddressOutputsObject <- jsonlite::fromJSON(Apiv1exploreraddressOutputsJson)
      self$`hours` <- Apiv1exploreraddressOutputsObject$`hours`
      self$`dst` <- Apiv1exploreraddressOutputsObject$`dst`
      self$`coins` <- Apiv1exploreraddressOutputsObject$`coins`
      self$`uxid` <- Apiv1exploreraddressOutputsObject$`uxid`
    }
  )
)
