# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1exploreraddressInputs Class
#'
#' @field owner 
#' @field hours 
#' @field calculated_hours 
#' @field coins 
#' @field uxid 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1exploreraddressInputs <- R6::R6Class(
  'Apiv1exploreraddressInputs',
  public = list(
    `owner` = NULL,
    `hours` = NULL,
    `calculated_hours` = NULL,
    `coins` = NULL,
    `uxid` = NULL,
    initialize = function(`owner`, `hours`, `calculated_hours`, `coins`, `uxid`){
      if (!missing(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!missing(`hours`)) {
        stopifnot(is.numeric(`hours`), length(`hours`) == 1)
        self$`hours` <- `hours`
      }
      if (!missing(`calculated_hours`)) {
        stopifnot(is.numeric(`calculated_hours`), length(`calculated_hours`) == 1)
        self$`calculated_hours` <- `calculated_hours`
      }
      if (!missing(`coins`)) {
        stopifnot(is.character(`coins`), length(`coins`) == 1)
        self$`coins` <- `coins`
      }
      if (!missing(`uxid`)) {
        stopifnot(is.character(`uxid`), length(`uxid`) == 1)
        self$`uxid` <- `uxid`
      }
    },
    toJSON = function() {
      Apiv1exploreraddressInputsObject <- list()
      if (!is.null(self$`owner`)) {
        Apiv1exploreraddressInputsObject[['owner']] <- self$`owner`
      }
      if (!is.null(self$`hours`)) {
        Apiv1exploreraddressInputsObject[['hours']] <- self$`hours`
      }
      if (!is.null(self$`calculated_hours`)) {
        Apiv1exploreraddressInputsObject[['calculated_hours']] <- self$`calculated_hours`
      }
      if (!is.null(self$`coins`)) {
        Apiv1exploreraddressInputsObject[['coins']] <- self$`coins`
      }
      if (!is.null(self$`uxid`)) {
        Apiv1exploreraddressInputsObject[['uxid']] <- self$`uxid`
      }

      Apiv1exploreraddressInputsObject
    },
    fromJSON = function(Apiv1exploreraddressInputsJson) {
      Apiv1exploreraddressInputsObject <- jsonlite::fromJSON(Apiv1exploreraddressInputsJson)
      if (!is.null(Apiv1exploreraddressInputsObject$`owner`)) {
        self$`owner` <- Apiv1exploreraddressInputsObject$`owner`
      }
      if (!is.null(Apiv1exploreraddressInputsObject$`hours`)) {
        self$`hours` <- Apiv1exploreraddressInputsObject$`hours`
      }
      if (!is.null(Apiv1exploreraddressInputsObject$`calculated_hours`)) {
        self$`calculated_hours` <- Apiv1exploreraddressInputsObject$`calculated_hours`
      }
      if (!is.null(Apiv1exploreraddressInputsObject$`coins`)) {
        self$`coins` <- Apiv1exploreraddressInputsObject$`coins`
      }
      if (!is.null(Apiv1exploreraddressInputsObject$`uxid`)) {
        self$`uxid` <- Apiv1exploreraddressInputsObject$`uxid`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "owner": %s,
           "hours": %d,
           "calculated_hours": %d,
           "coins": %s,
           "uxid": %s
        }',
        self$`owner`,
        self$`hours`,
        self$`calculated_hours`,
        self$`coins`,
        self$`uxid`
      )
    },
    fromJSONString = function(Apiv1exploreraddressInputsJson) {
      Apiv1exploreraddressInputsObject <- jsonlite::fromJSON(Apiv1exploreraddressInputsJson)
      self$`owner` <- Apiv1exploreraddressInputsObject$`owner`
      self$`hours` <- Apiv1exploreraddressInputsObject$`hours`
      self$`calculated_hours` <- Apiv1exploreraddressInputsObject$`calculated_hours`
      self$`coins` <- Apiv1exploreraddressInputsObject$`coins`
      self$`uxid` <- Apiv1exploreraddressInputsObject$`uxid`
    }
  )
)
