# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1wallettransactionTo Class
#'
#' @field hours 
#' @field address 
#' @field coins 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1wallettransactionTo <- R6::R6Class(
  'Apiv1wallettransactionTo',
  public = list(
    `hours` = NULL,
    `address` = NULL,
    `coins` = NULL,
    initialize = function(`hours`, `address`, `coins`){
      if (!missing(`hours`)) {
        stopifnot(is.numeric(`hours`), length(`hours`) == 1)
        self$`hours` <- `hours`
      }
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
      if (!missing(`coins`)) {
        stopifnot(is.numeric(`coins`), length(`coins`) == 1)
        self$`coins` <- `coins`
      }
    },
    toJSON = function() {
      Apiv1wallettransactionToObject <- list()
      if (!is.null(self$`hours`)) {
        Apiv1wallettransactionToObject[['hours']] <- self$`hours`
      }
      if (!is.null(self$`address`)) {
        Apiv1wallettransactionToObject[['address']] <- self$`address`
      }
      if (!is.null(self$`coins`)) {
        Apiv1wallettransactionToObject[['coins']] <- self$`coins`
      }

      Apiv1wallettransactionToObject
    },
    fromJSON = function(Apiv1wallettransactionToJson) {
      Apiv1wallettransactionToObject <- jsonlite::fromJSON(Apiv1wallettransactionToJson)
      if (!is.null(Apiv1wallettransactionToObject$`hours`)) {
        self$`hours` <- Apiv1wallettransactionToObject$`hours`
      }
      if (!is.null(Apiv1wallettransactionToObject$`address`)) {
        self$`address` <- Apiv1wallettransactionToObject$`address`
      }
      if (!is.null(Apiv1wallettransactionToObject$`coins`)) {
        self$`coins` <- Apiv1wallettransactionToObject$`coins`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hours": %d,
           "address": %s,
           "coins": %d
        }',
        self$`hours`,
        self$`address`,
        self$`coins`
      )
    },
    fromJSONString = function(Apiv1wallettransactionToJson) {
      Apiv1wallettransactionToObject <- jsonlite::fromJSON(Apiv1wallettransactionToJson)
      self$`hours` <- Apiv1wallettransactionToObject$`hours`
      self$`address` <- Apiv1wallettransactionToObject$`address`
      self$`coins` <- Apiv1wallettransactionToObject$`coins`
    }
  )
)
