# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1walletsEntries Class
#'
#' @field public_key 
#' @field address 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1walletsEntries <- R6::R6Class(
  'Apiv1walletsEntries',
  public = list(
    `public_key` = NULL,
    `address` = NULL,
    initialize = function(`public_key`, `address`){
      if (!missing(`public_key`)) {
        stopifnot(is.character(`public_key`), length(`public_key`) == 1)
        self$`public_key` <- `public_key`
      }
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
    },
    toJSON = function() {
      Apiv1walletsEntriesObject <- list()
      if (!is.null(self$`public_key`)) {
        Apiv1walletsEntriesObject[['public_key']] <- self$`public_key`
      }
      if (!is.null(self$`address`)) {
        Apiv1walletsEntriesObject[['address']] <- self$`address`
      }

      Apiv1walletsEntriesObject
    },
    fromJSON = function(Apiv1walletsEntriesJson) {
      Apiv1walletsEntriesObject <- jsonlite::fromJSON(Apiv1walletsEntriesJson)
      if (!is.null(Apiv1walletsEntriesObject$`public_key`)) {
        self$`public_key` <- Apiv1walletsEntriesObject$`public_key`
      }
      if (!is.null(Apiv1walletsEntriesObject$`address`)) {
        self$`address` <- Apiv1walletsEntriesObject$`address`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "public_key": %s,
           "address": %s
        }',
        self$`public_key`,
        self$`address`
      )
    },
    fromJSONString = function(Apiv1walletsEntriesJson) {
      Apiv1walletsEntriesObject <- jsonlite::fromJSON(Apiv1walletsEntriesJson)
      self$`public_key` <- Apiv1walletsEntriesObject$`public_key`
      self$`address` <- Apiv1walletsEntriesObject$`address`
    }
  )
)
