# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1wallettransactionWallet Class
#'
#' @field unspents 
#' @field addresses 
#' @field password 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1wallettransactionWallet <- R6::R6Class(
  'Apiv1wallettransactionWallet',
  public = list(
    `unspents` = NULL,
    `addresses` = NULL,
    `password` = NULL,
    `id` = NULL,
    initialize = function(`unspents`, `addresses`, `password`, `id`){
      if (!missing(`unspents`)) {
        stopifnot(is.list(`unspents`), length(`unspents`) != 0)
        lapply(`unspents`, function(x) stopifnot(is.character(x)))
        self$`unspents` <- `unspents`
      }
      if (!missing(`addresses`)) {
        stopifnot(is.list(`addresses`), length(`addresses`) != 0)
        lapply(`addresses`, function(x) stopifnot(is.character(x)))
        self$`addresses` <- `addresses`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      Apiv1wallettransactionWalletObject <- list()
      if (!is.null(self$`unspents`)) {
        Apiv1wallettransactionWalletObject[['unspents']] <- self$`unspents`
      }
      if (!is.null(self$`addresses`)) {
        Apiv1wallettransactionWalletObject[['addresses']] <- self$`addresses`
      }
      if (!is.null(self$`password`)) {
        Apiv1wallettransactionWalletObject[['password']] <- self$`password`
      }
      if (!is.null(self$`id`)) {
        Apiv1wallettransactionWalletObject[['id']] <- self$`id`
      }

      Apiv1wallettransactionWalletObject
    },
    fromJSON = function(Apiv1wallettransactionWalletJson) {
      Apiv1wallettransactionWalletObject <- jsonlite::fromJSON(Apiv1wallettransactionWalletJson)
      if (!is.null(Apiv1wallettransactionWalletObject$`unspents`)) {
        self$`unspents` <- Apiv1wallettransactionWalletObject$`unspents`
      }
      if (!is.null(Apiv1wallettransactionWalletObject$`addresses`)) {
        self$`addresses` <- Apiv1wallettransactionWalletObject$`addresses`
      }
      if (!is.null(Apiv1wallettransactionWalletObject$`password`)) {
        self$`password` <- Apiv1wallettransactionWalletObject$`password`
      }
      if (!is.null(Apiv1wallettransactionWalletObject$`id`)) {
        self$`id` <- Apiv1wallettransactionWalletObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "unspents": [%s],
           "addresses": [%s],
           "password": %s,
           "id": %s
        }',
        lapply(self$`unspents`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`addresses`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`password`,
        self$`id`
      )
    },
    fromJSONString = function(Apiv1wallettransactionWalletJson) {
      Apiv1wallettransactionWalletObject <- jsonlite::fromJSON(Apiv1wallettransactionWalletJson)
      self$`unspents` <- Apiv1wallettransactionWalletObject$`unspents`
      self$`addresses` <- Apiv1wallettransactionWalletObject$`addresses`
      self$`password` <- Apiv1wallettransactionWalletObject$`password`
      self$`id` <- Apiv1wallettransactionWalletObject$`id`
    }
  )
)
