# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' Apiv1wallettransactionHoursSelection Class
#'
#' @field mode 
#' @field share_factor 
#' @field type 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Apiv1wallettransactionHoursSelection <- R6::R6Class(
  'Apiv1wallettransactionHoursSelection',
  public = list(
    `mode` = NULL,
    `share_factor` = NULL,
    `type` = NULL,
    initialize = function(`mode`, `share_factor`, `type`){
      if (!missing(`mode`)) {
        stopifnot(is.character(`mode`), length(`mode`) == 1)
        self$`mode` <- `mode`
      }
      if (!missing(`share_factor`)) {
        stopifnot(is.character(`share_factor`), length(`share_factor`) == 1)
        self$`share_factor` <- `share_factor`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      Apiv1wallettransactionHoursSelectionObject <- list()
      if (!is.null(self$`mode`)) {
        Apiv1wallettransactionHoursSelectionObject[['mode']] <- self$`mode`
      }
      if (!is.null(self$`share_factor`)) {
        Apiv1wallettransactionHoursSelectionObject[['share_factor']] <- self$`share_factor`
      }
      if (!is.null(self$`type`)) {
        Apiv1wallettransactionHoursSelectionObject[['type']] <- self$`type`
      }

      Apiv1wallettransactionHoursSelectionObject
    },
    fromJSON = function(Apiv1wallettransactionHoursSelectionJson) {
      Apiv1wallettransactionHoursSelectionObject <- jsonlite::fromJSON(Apiv1wallettransactionHoursSelectionJson)
      if (!is.null(Apiv1wallettransactionHoursSelectionObject$`mode`)) {
        self$`mode` <- Apiv1wallettransactionHoursSelectionObject$`mode`
      }
      if (!is.null(Apiv1wallettransactionHoursSelectionObject$`share_factor`)) {
        self$`share_factor` <- Apiv1wallettransactionHoursSelectionObject$`share_factor`
      }
      if (!is.null(Apiv1wallettransactionHoursSelectionObject$`type`)) {
        self$`type` <- Apiv1wallettransactionHoursSelectionObject$`type`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "mode": %s,
           "share_factor": %s,
           "type": %s
        }',
        self$`mode`,
        self$`share_factor`,
        self$`type`
      )
    },
    fromJSONString = function(Apiv1wallettransactionHoursSelectionJson) {
      Apiv1wallettransactionHoursSelectionObject <- jsonlite::fromJSON(Apiv1wallettransactionHoursSelectionJson)
      self$`mode` <- Apiv1wallettransactionHoursSelectionObject$`mode`
      self$`share_factor` <- Apiv1wallettransactionHoursSelectionObject$`share_factor`
      self$`type` <- Apiv1wallettransactionHoursSelectionObject$`type`
    }
  )
)
