# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2007Data Class
#'
#' @field version 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2007Data <- R6::R6Class(
  'InlineResponse2007Data',
  public = list(
    `version` = NULL,
    initialize = function(`version`){
      if (!missing(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      InlineResponse2007DataObject <- list()
      if (!is.null(self$`version`)) {
        InlineResponse2007DataObject[['version']] <- self$`version`
      }

      InlineResponse2007DataObject
    },
    fromJSON = function(InlineResponse2007DataJson) {
      InlineResponse2007DataObject <- jsonlite::fromJSON(InlineResponse2007DataJson)
      if (!is.null(InlineResponse2007DataObject$`version`)) {
        self$`version` <- InlineResponse2007DataObject$`version`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "version": %d
        }',
        self$`version`
      )
    },
    fromJSONString = function(InlineResponse2007DataJson) {
      InlineResponse2007DataObject <- jsonlite::fromJSON(InlineResponse2007DataJson)
      self$`version` <- InlineResponse2007DataObject$`version`
    }
  )
)
