# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2006 Class
#'
#' @field address 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2006 <- R6::R6Class(
  'InlineResponse2006',
  public = list(
    `address` = NULL,
    initialize = function(`address`){
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
    },
    toJSON = function() {
      InlineResponse2006Object <- list()
      if (!is.null(self$`address`)) {
        InlineResponse2006Object[['address']] <- self$`address`
      }

      InlineResponse2006Object
    },
    fromJSON = function(InlineResponse2006Json) {
      InlineResponse2006Object <- jsonlite::fromJSON(InlineResponse2006Json)
      if (!is.null(InlineResponse2006Object$`address`)) {
        self$`address` <- InlineResponse2006Object$`address`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "address": %s
        }',
        self$`address`
      )
    },
    fromJSONString = function(InlineResponse2006Json) {
      InlineResponse2006Object <- jsonlite::fromJSON(InlineResponse2006Json)
      self$`address` <- InlineResponse2006Object$`address`
    }
  )
)
