# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2003 Class
#'
#' @field last_received 
#' @field last_sent 
#' @field outgoing 
#' @field mirror 
#' @field address 
#' @field listen_port 
#' @field is_trusted_peer 
#' @field connected_at 
#' @field unconfirmed_verify_transaction 
#' @field id 
#' @field state 
#' @field user_agent 
#' @field height 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2003 <- R6::R6Class(
  'InlineResponse2003',
  public = list(
    `last_received` = NULL,
    `last_sent` = NULL,
    `outgoing` = NULL,
    `mirror` = NULL,
    `address` = NULL,
    `listen_port` = NULL,
    `is_trusted_peer` = NULL,
    `connected_at` = NULL,
    `unconfirmed_verify_transaction` = NULL,
    `id` = NULL,
    `state` = NULL,
    `user_agent` = NULL,
    `height` = NULL,
    initialize = function(`last_received`, `last_sent`, `outgoing`, `mirror`, `address`, `listen_port`, `is_trusted_peer`, `connected_at`, `unconfirmed_verify_transaction`, `id`, `state`, `user_agent`, `height`){
      if (!missing(`last_received`)) {
        stopifnot(is.numeric(`last_received`), length(`last_received`) == 1)
        self$`last_received` <- `last_received`
      }
      if (!missing(`last_sent`)) {
        stopifnot(is.numeric(`last_sent`), length(`last_sent`) == 1)
        self$`last_sent` <- `last_sent`
      }
      if (!missing(`outgoing`)) {
        self$`outgoing` <- `outgoing`
      }
      if (!missing(`mirror`)) {
        stopifnot(is.numeric(`mirror`), length(`mirror`) == 1)
        self$`mirror` <- `mirror`
      }
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
      if (!missing(`listen_port`)) {
        stopifnot(is.numeric(`listen_port`), length(`listen_port`) == 1)
        self$`listen_port` <- `listen_port`
      }
      if (!missing(`is_trusted_peer`)) {
        self$`is_trusted_peer` <- `is_trusted_peer`
      }
      if (!missing(`connected_at`)) {
        stopifnot(is.numeric(`connected_at`), length(`connected_at`) == 1)
        self$`connected_at` <- `connected_at`
      }
      if (!missing(`unconfirmed_verify_transaction`)) {
        stopifnot(R6::is.R6(`unconfirmed_verify_transaction`))
        self$`unconfirmed_verify_transaction` <- `unconfirmed_verify_transaction`
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`user_agent`)) {
        stopifnot(is.character(`user_agent`), length(`user_agent`) == 1)
        self$`user_agent` <- `user_agent`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
    },
    toJSON = function() {
      InlineResponse2003Object <- list()
      if (!is.null(self$`last_received`)) {
        InlineResponse2003Object[['last_received']] <- self$`last_received`
      }
      if (!is.null(self$`last_sent`)) {
        InlineResponse2003Object[['last_sent']] <- self$`last_sent`
      }
      if (!is.null(self$`outgoing`)) {
        InlineResponse2003Object[['outgoing']] <- self$`outgoing`
      }
      if (!is.null(self$`mirror`)) {
        InlineResponse2003Object[['mirror']] <- self$`mirror`
      }
      if (!is.null(self$`address`)) {
        InlineResponse2003Object[['address']] <- self$`address`
      }
      if (!is.null(self$`listen_port`)) {
        InlineResponse2003Object[['listen_port']] <- self$`listen_port`
      }
      if (!is.null(self$`is_trusted_peer`)) {
        InlineResponse2003Object[['is_trusted_peer']] <- self$`is_trusted_peer`
      }
      if (!is.null(self$`connected_at`)) {
        InlineResponse2003Object[['connected_at']] <- self$`connected_at`
      }
      if (!is.null(self$`unconfirmed_verify_transaction`)) {
        InlineResponse2003Object[['unconfirmed_verify_transaction']] <- self$`unconfirmed_verify_transaction`$toJSON()
      }
      if (!is.null(self$`id`)) {
        InlineResponse2003Object[['id']] <- self$`id`
      }
      if (!is.null(self$`state`)) {
        InlineResponse2003Object[['state']] <- self$`state`
      }
      if (!is.null(self$`user_agent`)) {
        InlineResponse2003Object[['user_agent']] <- self$`user_agent`
      }
      if (!is.null(self$`height`)) {
        InlineResponse2003Object[['height']] <- self$`height`
      }

      InlineResponse2003Object
    },
    fromJSON = function(InlineResponse2003Json) {
      InlineResponse2003Object <- jsonlite::fromJSON(InlineResponse2003Json)
      if (!is.null(InlineResponse2003Object$`last_received`)) {
        self$`last_received` <- InlineResponse2003Object$`last_received`
      }
      if (!is.null(InlineResponse2003Object$`last_sent`)) {
        self$`last_sent` <- InlineResponse2003Object$`last_sent`
      }
      if (!is.null(InlineResponse2003Object$`outgoing`)) {
        self$`outgoing` <- InlineResponse2003Object$`outgoing`
      }
      if (!is.null(InlineResponse2003Object$`mirror`)) {
        self$`mirror` <- InlineResponse2003Object$`mirror`
      }
      if (!is.null(InlineResponse2003Object$`address`)) {
        self$`address` <- InlineResponse2003Object$`address`
      }
      if (!is.null(InlineResponse2003Object$`listen_port`)) {
        self$`listen_port` <- InlineResponse2003Object$`listen_port`
      }
      if (!is.null(InlineResponse2003Object$`is_trusted_peer`)) {
        self$`is_trusted_peer` <- InlineResponse2003Object$`is_trusted_peer`
      }
      if (!is.null(InlineResponse2003Object$`connected_at`)) {
        self$`connected_at` <- InlineResponse2003Object$`connected_at`
      }
      if (!is.null(InlineResponse2003Object$`unconfirmed_verify_transaction`)) {
        unconfirmed_verify_transactionObject <- InlineResponse2003UnconfirmedVerifyTransaction$new()
        unconfirmed_verify_transactionObject$fromJSON(jsonlite::toJSON(InlineResponse2003Object$unconfirmed_verify_transaction, auto_unbox = TRUE))
        self$`unconfirmed_verify_transaction` <- unconfirmed_verify_transactionObject
      }
      if (!is.null(InlineResponse2003Object$`id`)) {
        self$`id` <- InlineResponse2003Object$`id`
      }
      if (!is.null(InlineResponse2003Object$`state`)) {
        self$`state` <- InlineResponse2003Object$`state`
      }
      if (!is.null(InlineResponse2003Object$`user_agent`)) {
        self$`user_agent` <- InlineResponse2003Object$`user_agent`
      }
      if (!is.null(InlineResponse2003Object$`height`)) {
        self$`height` <- InlineResponse2003Object$`height`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "last_received": %d,
           "last_sent": %d,
           "outgoing": %s,
           "mirror": %d,
           "address": %s,
           "listen_port": %d,
           "is_trusted_peer": %s,
           "connected_at": %d,
           "unconfirmed_verify_transaction": %s,
           "id": %d,
           "state": %s,
           "user_agent": %s,
           "height": %d
        }',
        self$`last_received`,
        self$`last_sent`,
        self$`outgoing`,
        self$`mirror`,
        self$`address`,
        self$`listen_port`,
        self$`is_trusted_peer`,
        self$`connected_at`,
        self$`unconfirmed_verify_transaction`$toJSON(),
        self$`id`,
        self$`state`,
        self$`user_agent`,
        self$`height`
      )
    },
    fromJSONString = function(InlineResponse2003Json) {
      InlineResponse2003Object <- jsonlite::fromJSON(InlineResponse2003Json)
      self$`last_received` <- InlineResponse2003Object$`last_received`
      self$`last_sent` <- InlineResponse2003Object$`last_sent`
      self$`outgoing` <- InlineResponse2003Object$`outgoing`
      self$`mirror` <- InlineResponse2003Object$`mirror`
      self$`address` <- InlineResponse2003Object$`address`
      self$`listen_port` <- InlineResponse2003Object$`listen_port`
      self$`is_trusted_peer` <- InlineResponse2003Object$`is_trusted_peer`
      self$`connected_at` <- InlineResponse2003Object$`connected_at`
      InlineResponse2003UnconfirmedVerifyTransactionObject <- InlineResponse2003UnconfirmedVerifyTransaction$new()
      self$`unconfirmed_verify_transaction` <- InlineResponse2003UnconfirmedVerifyTransactionObject$fromJSON(jsonlite::toJSON(InlineResponse2003Object$unconfirmed_verify_transaction, auto_unbox = TRUE))
      self$`id` <- InlineResponse2003Object$`id`
      self$`state` <- InlineResponse2003Object$`state`
      self$`user_agent` <- InlineResponse2003Object$`user_agent`
      self$`height` <- InlineResponse2003Object$`height`
    }
  )
)
