# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponseDefault Class
#'
#' @field code 
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponseDefault <- R6::R6Class(
  'InlineResponseDefault',
  public = list(
    `code` = NULL,
    `message` = NULL,
    initialize = function(`code`, `message`){
      if (!missing(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      InlineResponseDefaultObject <- list()
      if (!is.null(self$`code`)) {
        InlineResponseDefaultObject[['code']] <- self$`code`
      }
      if (!is.null(self$`message`)) {
        InlineResponseDefaultObject[['message']] <- self$`message`
      }

      InlineResponseDefaultObject
    },
    fromJSON = function(InlineResponseDefaultJson) {
      InlineResponseDefaultObject <- jsonlite::fromJSON(InlineResponseDefaultJson)
      if (!is.null(InlineResponseDefaultObject$`code`)) {
        self$`code` <- InlineResponseDefaultObject$`code`
      }
      if (!is.null(InlineResponseDefaultObject$`message`)) {
        self$`message` <- InlineResponseDefaultObject$`message`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "code": %d,
           "message": %s
        }',
        self$`code`,
        self$`message`
      )
    },
    fromJSONString = function(InlineResponseDefaultJson) {
      InlineResponseDefaultObject <- jsonlite::fromJSON(InlineResponseDefaultJson)
      self$`code` <- InlineResponseDefaultObject$`code`
      self$`message` <- InlineResponseDefaultObject$`message`
    }
  )
)
