# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2003UnconfirmedVerifyTransaction Class
#'
#' @field burn_factor 
#' @field max_transaction_size 
#' @field max_decimals 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2003UnconfirmedVerifyTransaction <- R6::R6Class(
  'InlineResponse2003UnconfirmedVerifyTransaction',
  public = list(
    `burn_factor` = NULL,
    `max_transaction_size` = NULL,
    `max_decimals` = NULL,
    initialize = function(`burn_factor`, `max_transaction_size`, `max_decimals`){
      if (!missing(`burn_factor`)) {
        stopifnot(is.numeric(`burn_factor`), length(`burn_factor`) == 1)
        self$`burn_factor` <- `burn_factor`
      }
      if (!missing(`max_transaction_size`)) {
        stopifnot(is.numeric(`max_transaction_size`), length(`max_transaction_size`) == 1)
        self$`max_transaction_size` <- `max_transaction_size`
      }
      if (!missing(`max_decimals`)) {
        stopifnot(is.numeric(`max_decimals`), length(`max_decimals`) == 1)
        self$`max_decimals` <- `max_decimals`
      }
    },
    toJSON = function() {
      InlineResponse2003UnconfirmedVerifyTransactionObject <- list()
      if (!is.null(self$`burn_factor`)) {
        InlineResponse2003UnconfirmedVerifyTransactionObject[['burn_factor']] <- self$`burn_factor`
      }
      if (!is.null(self$`max_transaction_size`)) {
        InlineResponse2003UnconfirmedVerifyTransactionObject[['max_transaction_size']] <- self$`max_transaction_size`
      }
      if (!is.null(self$`max_decimals`)) {
        InlineResponse2003UnconfirmedVerifyTransactionObject[['max_decimals']] <- self$`max_decimals`
      }

      InlineResponse2003UnconfirmedVerifyTransactionObject
    },
    fromJSON = function(InlineResponse2003UnconfirmedVerifyTransactionJson) {
      InlineResponse2003UnconfirmedVerifyTransactionObject <- jsonlite::fromJSON(InlineResponse2003UnconfirmedVerifyTransactionJson)
      if (!is.null(InlineResponse2003UnconfirmedVerifyTransactionObject$`burn_factor`)) {
        self$`burn_factor` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`burn_factor`
      }
      if (!is.null(InlineResponse2003UnconfirmedVerifyTransactionObject$`max_transaction_size`)) {
        self$`max_transaction_size` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`max_transaction_size`
      }
      if (!is.null(InlineResponse2003UnconfirmedVerifyTransactionObject$`max_decimals`)) {
        self$`max_decimals` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`max_decimals`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "burn_factor": %d,
           "max_transaction_size": %d,
           "max_decimals": %d
        }',
        self$`burn_factor`,
        self$`max_transaction_size`,
        self$`max_decimals`
      )
    },
    fromJSONString = function(InlineResponse2003UnconfirmedVerifyTransactionJson) {
      InlineResponse2003UnconfirmedVerifyTransactionObject <- jsonlite::fromJSON(InlineResponse2003UnconfirmedVerifyTransactionJson)
      self$`burn_factor` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`burn_factor`
      self$`max_transaction_size` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`max_transaction_size`
      self$`max_decimals` <- InlineResponse2003UnconfirmedVerifyTransactionObject$`max_decimals`
    }
  )
)
