# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2005 Class
#'
#' @field entries 
#' @field meta 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2005 <- R6::R6Class(
  'InlineResponse2005',
  public = list(
    `entries` = NULL,
    `meta` = NULL,
    initialize = function(`entries`, `meta`){
      if (!missing(`entries`)) {
        stopifnot(is.list(`entries`), length(`entries`) != 0)
        lapply(`entries`, function(x) stopifnot(R6::is.R6(x)))
        self$`entries` <- `entries`
      }
      if (!missing(`meta`)) {
        stopifnot(R6::is.R6(`meta`))
        self$`meta` <- `meta`
      }
    },
    toJSON = function() {
      InlineResponse2005Object <- list()
      if (!is.null(self$`entries`)) {
        InlineResponse2005Object[['entries']] <- lapply(self$`entries`, function(x) x$toJSON())
      }
      if (!is.null(self$`meta`)) {
        InlineResponse2005Object[['meta']] <- self$`meta`$toJSON()
      }

      InlineResponse2005Object
    },
    fromJSON = function(InlineResponse2005Json) {
      InlineResponse2005Object <- jsonlite::fromJSON(InlineResponse2005Json)
      if (!is.null(InlineResponse2005Object$`entries`)) {
        self$`entries` <- lapply(InlineResponse2005Object$`entries`, function(x) {
          entriesObject <- Apiv1walletsEntries$new()
          entriesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          entriesObject
        })
      }
      if (!is.null(InlineResponse2005Object$`meta`)) {
        metaObject <- Apiv1walletsMeta$new()
        metaObject$fromJSON(jsonlite::toJSON(InlineResponse2005Object$meta, auto_unbox = TRUE))
        self$`meta` <- metaObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "entries": [%s],
           "meta": %s
        }',
        lapply(self$`entries`, function(x) paste(x$toJSON(), sep=",")),
        self$`meta`$toJSON()
      )
    },
    fromJSONString = function(InlineResponse2005Json) {
      InlineResponse2005Object <- jsonlite::fromJSON(InlineResponse2005Json)
      self$`entries` <- lapply(InlineResponse2005Object$`entries`, function(x) Apiv1walletsEntries$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      Apiv1walletsMetaObject <- Apiv1walletsMeta$new()
      self$`meta` <- Apiv1walletsMetaObject$fromJSON(jsonlite::toJSON(InlineResponse2005Object$meta, auto_unbox = TRUE))
    }
  )
)
