# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2007 Class
#'
#' @field data 
#' @field error 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2007 <- R6::R6Class(
  'InlineResponse2007',
  public = list(
    `data` = NULL,
    `error` = NULL,
    initialize = function(`data`, `error`){
      if (!missing(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
      if (!missing(`error`)) {
        stopifnot(R6::is.R6(`error`))
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      InlineResponse2007Object <- list()
      if (!is.null(self$`data`)) {
        InlineResponse2007Object[['data']] <- self$`data`$toJSON()
      }
      if (!is.null(self$`error`)) {
        InlineResponse2007Object[['error']] <- self$`error`$toJSON()
      }

      InlineResponse2007Object
    },
    fromJSON = function(InlineResponse2007Json) {
      InlineResponse2007Object <- jsonlite::fromJSON(InlineResponse2007Json)
      if (!is.null(InlineResponse2007Object$`data`)) {
        dataObject <- InlineResponse2007Data$new()
        dataObject$fromJSON(jsonlite::toJSON(InlineResponse2007Object$data, auto_unbox = TRUE))
        self$`data` <- dataObject
      }
      if (!is.null(InlineResponse2007Object$`error`)) {
        errorObject <- object$new()
        errorObject$fromJSON(jsonlite::toJSON(InlineResponse2007Object$error, auto_unbox = TRUE))
        self$`error` <- errorObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "data": %s,
           "error": %s
        }',
        self$`data`$toJSON(),
        self$`error`$toJSON()
      )
    },
    fromJSONString = function(InlineResponse2007Json) {
      InlineResponse2007Object <- jsonlite::fromJSON(InlineResponse2007Json)
      InlineResponse2007DataObject <- InlineResponse2007Data$new()
      self$`data` <- InlineResponse2007DataObject$fromJSON(jsonlite::toJSON(InlineResponse2007Object$data, auto_unbox = TRUE))
      objectObject <- object$new()
      self$`error` <- objectObject$fromJSON(jsonlite::toJSON(InlineResponse2007Object$error, auto_unbox = TRUE))
    }
  )
)
