# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2004 Class
#'
#' @field announced 
#' @field is_valid 
#' @field checked 
#' @field received 
#' @field transaction 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2004 <- R6::R6Class(
  'InlineResponse2004',
  public = list(
    `announced` = NULL,
    `is_valid` = NULL,
    `checked` = NULL,
    `received` = NULL,
    `transaction` = NULL,
    initialize = function(`announced`, `is_valid`, `checked`, `received`, `transaction`){
      if (!missing(`announced`)) {
        stopifnot(is.character(`announced`), length(`announced`) == 1)
        self$`announced` <- `announced`
      }
      if (!missing(`is_valid`)) {
        self$`is_valid` <- `is_valid`
      }
      if (!missing(`checked`)) {
        stopifnot(is.character(`checked`), length(`checked`) == 1)
        self$`checked` <- `checked`
      }
      if (!missing(`received`)) {
        stopifnot(is.character(`received`), length(`received`) == 1)
        self$`received` <- `received`
      }
      if (!missing(`transaction`)) {
        stopifnot(R6::is.R6(`transaction`))
        self$`transaction` <- `transaction`
      }
    },
    toJSON = function() {
      InlineResponse2004Object <- list()
      if (!is.null(self$`announced`)) {
        InlineResponse2004Object[['announced']] <- self$`announced`
      }
      if (!is.null(self$`is_valid`)) {
        InlineResponse2004Object[['is_valid']] <- self$`is_valid`
      }
      if (!is.null(self$`checked`)) {
        InlineResponse2004Object[['checked']] <- self$`checked`
      }
      if (!is.null(self$`received`)) {
        InlineResponse2004Object[['received']] <- self$`received`
      }
      if (!is.null(self$`transaction`)) {
        InlineResponse2004Object[['transaction']] <- self$`transaction`$toJSON()
      }

      InlineResponse2004Object
    },
    fromJSON = function(InlineResponse2004Json) {
      InlineResponse2004Object <- jsonlite::fromJSON(InlineResponse2004Json)
      if (!is.null(InlineResponse2004Object$`announced`)) {
        self$`announced` <- InlineResponse2004Object$`announced`
      }
      if (!is.null(InlineResponse2004Object$`is_valid`)) {
        self$`is_valid` <- InlineResponse2004Object$`is_valid`
      }
      if (!is.null(InlineResponse2004Object$`checked`)) {
        self$`checked` <- InlineResponse2004Object$`checked`
      }
      if (!is.null(InlineResponse2004Object$`received`)) {
        self$`received` <- InlineResponse2004Object$`received`
      }
      if (!is.null(InlineResponse2004Object$`transaction`)) {
        transactionObject <- Apiv1pendingTxsTransaction$new()
        transactionObject$fromJSON(jsonlite::toJSON(InlineResponse2004Object$transaction, auto_unbox = TRUE))
        self$`transaction` <- transactionObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "announced": %s,
           "is_valid": %s,
           "checked": %s,
           "received": %s,
           "transaction": %s
        }',
        self$`announced`,
        self$`is_valid`,
        self$`checked`,
        self$`received`,
        self$`transaction`$toJSON()
      )
    },
    fromJSONString = function(InlineResponse2004Json) {
      InlineResponse2004Object <- jsonlite::fromJSON(InlineResponse2004Json)
      self$`announced` <- InlineResponse2004Object$`announced`
      self$`is_valid` <- InlineResponse2004Object$`is_valid`
      self$`checked` <- InlineResponse2004Object$`checked`
      self$`received` <- InlineResponse2004Object$`received`
      Apiv1pendingTxsTransactionObject <- Apiv1pendingTxsTransaction$new()
      self$`transaction` <- Apiv1pendingTxsTransactionObject$fromJSON(jsonlite::toJSON(InlineResponse2004Object$transaction, auto_unbox = TRUE))
    }
  )
)
