# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2002 Class
#'
#' @field outputs 
#' @field inner_hash 
#' @field inputs 
#' @field fee 
#' @field sigs 
#' @field length 
#' @field txid 
#' @field type 
#' @field status 
#' @field timestamp 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2002 <- R6::R6Class(
  'InlineResponse2002',
  public = list(
    `outputs` = NULL,
    `inner_hash` = NULL,
    `inputs` = NULL,
    `fee` = NULL,
    `sigs` = NULL,
    `length` = NULL,
    `txid` = NULL,
    `type` = NULL,
    `status` = NULL,
    `timestamp` = NULL,
    initialize = function(`outputs`, `inner_hash`, `inputs`, `fee`, `sigs`, `length`, `txid`, `type`, `status`, `timestamp`){
      if (!missing(`outputs`)) {
        stopifnot(is.list(`outputs`), length(`outputs`) != 0)
        lapply(`outputs`, function(x) stopifnot(R6::is.R6(x)))
        self$`outputs` <- `outputs`
      }
      if (!missing(`inner_hash`)) {
        stopifnot(is.character(`inner_hash`), length(`inner_hash`) == 1)
        self$`inner_hash` <- `inner_hash`
      }
      if (!missing(`inputs`)) {
        stopifnot(is.list(`inputs`), length(`inputs`) != 0)
        lapply(`inputs`, function(x) stopifnot(R6::is.R6(x)))
        self$`inputs` <- `inputs`
      }
      if (!missing(`fee`)) {
        stopifnot(is.numeric(`fee`), length(`fee`) == 1)
        self$`fee` <- `fee`
      }
      if (!missing(`sigs`)) {
        stopifnot(is.list(`sigs`), length(`sigs`) != 0)
        lapply(`sigs`, function(x) stopifnot(is.character(x)))
        self$`sigs` <- `sigs`
      }
      if (!missing(`length`)) {
        stopifnot(is.numeric(`length`), length(`length`) == 1)
        self$`length` <- `length`
      }
      if (!missing(`txid`)) {
        stopifnot(is.character(`txid`), length(`txid`) == 1)
        self$`txid` <- `txid`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
    },
    toJSON = function() {
      InlineResponse2002Object <- list()
      if (!is.null(self$`outputs`)) {
        InlineResponse2002Object[['outputs']] <- lapply(self$`outputs`, function(x) x$toJSON())
      }
      if (!is.null(self$`inner_hash`)) {
        InlineResponse2002Object[['inner_hash']] <- self$`inner_hash`
      }
      if (!is.null(self$`inputs`)) {
        InlineResponse2002Object[['inputs']] <- lapply(self$`inputs`, function(x) x$toJSON())
      }
      if (!is.null(self$`fee`)) {
        InlineResponse2002Object[['fee']] <- self$`fee`
      }
      if (!is.null(self$`sigs`)) {
        InlineResponse2002Object[['sigs']] <- self$`sigs`
      }
      if (!is.null(self$`length`)) {
        InlineResponse2002Object[['length']] <- self$`length`
      }
      if (!is.null(self$`txid`)) {
        InlineResponse2002Object[['txid']] <- self$`txid`
      }
      if (!is.null(self$`type`)) {
        InlineResponse2002Object[['type']] <- self$`type`
      }
      if (!is.null(self$`status`)) {
        InlineResponse2002Object[['status']] <- self$`status`$toJSON()
      }
      if (!is.null(self$`timestamp`)) {
        InlineResponse2002Object[['timestamp']] <- self$`timestamp`
      }

      InlineResponse2002Object
    },
    fromJSON = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      if (!is.null(InlineResponse2002Object$`outputs`)) {
        self$`outputs` <- lapply(InlineResponse2002Object$`outputs`, function(x) {
          outputsObject <- Apiv1exploreraddressOutputs$new()
          outputsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          outputsObject
        })
      }
      if (!is.null(InlineResponse2002Object$`inner_hash`)) {
        self$`inner_hash` <- InlineResponse2002Object$`inner_hash`
      }
      if (!is.null(InlineResponse2002Object$`inputs`)) {
        self$`inputs` <- lapply(InlineResponse2002Object$`inputs`, function(x) {
          inputsObject <- Apiv1exploreraddressInputs$new()
          inputsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          inputsObject
        })
      }
      if (!is.null(InlineResponse2002Object$`fee`)) {
        self$`fee` <- InlineResponse2002Object$`fee`
      }
      if (!is.null(InlineResponse2002Object$`sigs`)) {
        self$`sigs` <- InlineResponse2002Object$`sigs`
      }
      if (!is.null(InlineResponse2002Object$`length`)) {
        self$`length` <- InlineResponse2002Object$`length`
      }
      if (!is.null(InlineResponse2002Object$`txid`)) {
        self$`txid` <- InlineResponse2002Object$`txid`
      }
      if (!is.null(InlineResponse2002Object$`type`)) {
        self$`type` <- InlineResponse2002Object$`type`
      }
      if (!is.null(InlineResponse2002Object$`status`)) {
        statusObject <- Apiv1exploreraddressStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(InlineResponse2002Object$status, auto_unbox = TRUE))
        self$`status` <- statusObject
      }
      if (!is.null(InlineResponse2002Object$`timestamp`)) {
        self$`timestamp` <- InlineResponse2002Object$`timestamp`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "outputs": [%s],
           "inner_hash": %s,
           "inputs": [%s],
           "fee": %d,
           "sigs": [%s],
           "length": %d,
           "txid": %s,
           "type": %d,
           "status": %s,
           "timestamp": %d
        }',
        lapply(self$`outputs`, function(x) paste(x$toJSON(), sep=",")),
        self$`inner_hash`,
        lapply(self$`inputs`, function(x) paste(x$toJSON(), sep=",")),
        self$`fee`,
        lapply(self$`sigs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`length`,
        self$`txid`,
        self$`type`,
        self$`status`$toJSON(),
        self$`timestamp`
      )
    },
    fromJSONString = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      self$`outputs` <- lapply(InlineResponse2002Object$`outputs`, function(x) Apiv1exploreraddressOutputs$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`inner_hash` <- InlineResponse2002Object$`inner_hash`
      self$`inputs` <- lapply(InlineResponse2002Object$`inputs`, function(x) Apiv1exploreraddressInputs$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`fee` <- InlineResponse2002Object$`fee`
      self$`sigs` <- InlineResponse2002Object$`sigs`
      self$`length` <- InlineResponse2002Object$`length`
      self$`txid` <- InlineResponse2002Object$`txid`
      self$`type` <- InlineResponse2002Object$`type`
      Apiv1exploreraddressStatusObject <- Apiv1exploreraddressStatus$new()
      self$`status` <- Apiv1exploreraddressStatusObject$fromJSON(jsonlite::toJSON(InlineResponse2002Object$status, auto_unbox = TRUE))
      self$`timestamp` <- InlineResponse2002Object$`timestamp`
    }
  )
)
