# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse2001 Class
#'
#' @field csrf_token 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2001 <- R6::R6Class(
  'InlineResponse2001',
  public = list(
    `csrf_token` = NULL,
    initialize = function(`csrf_token`){
      if (!missing(`csrf_token`)) {
        stopifnot(is.character(`csrf_token`), length(`csrf_token`) == 1)
        self$`csrf_token` <- `csrf_token`
      }
    },
    toJSON = function() {
      InlineResponse2001Object <- list()
      if (!is.null(self$`csrf_token`)) {
        InlineResponse2001Object[['csrf_token']] <- self$`csrf_token`
      }

      InlineResponse2001Object
    },
    fromJSON = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      if (!is.null(InlineResponse2001Object$`csrf_token`)) {
        self$`csrf_token` <- InlineResponse2001Object$`csrf_token`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "csrf_token": %s
        }',
        self$`csrf_token`
      )
    },
    fromJSONString = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      self$`csrf_token` <- InlineResponse2001Object$`csrf_token`
    }
  )
)
