# Skycoin REST API.
#
# Skycoin is a next-generation cryptocurrency.
#
# OpenAPI spec version: 0.25.1
# Contact: contact@skycoin.net
# Generated by: https://openapi-generator.tech


#' InlineResponse200 Class
#'
#' @field hours 
#' @field coins 
#' @field uxid 
#' @field owner_address 
#' @field spent_block_seq 
#' @field spent_tx 
#' @field time 
#' @field src_block_seq 
#' @field src_tx 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200 <- R6::R6Class(
  'InlineResponse200',
  public = list(
    `hours` = NULL,
    `coins` = NULL,
    `uxid` = NULL,
    `owner_address` = NULL,
    `spent_block_seq` = NULL,
    `spent_tx` = NULL,
    `time` = NULL,
    `src_block_seq` = NULL,
    `src_tx` = NULL,
    initialize = function(`hours`, `coins`, `uxid`, `owner_address`, `spent_block_seq`, `spent_tx`, `time`, `src_block_seq`, `src_tx`){
      if (!missing(`hours`)) {
        stopifnot(is.numeric(`hours`), length(`hours`) == 1)
        self$`hours` <- `hours`
      }
      if (!missing(`coins`)) {
        stopifnot(is.numeric(`coins`), length(`coins`) == 1)
        self$`coins` <- `coins`
      }
      if (!missing(`uxid`)) {
        stopifnot(is.character(`uxid`), length(`uxid`) == 1)
        self$`uxid` <- `uxid`
      }
      if (!missing(`owner_address`)) {
        stopifnot(is.character(`owner_address`), length(`owner_address`) == 1)
        self$`owner_address` <- `owner_address`
      }
      if (!missing(`spent_block_seq`)) {
        stopifnot(is.numeric(`spent_block_seq`), length(`spent_block_seq`) == 1)
        self$`spent_block_seq` <- `spent_block_seq`
      }
      if (!missing(`spent_tx`)) {
        stopifnot(is.character(`spent_tx`), length(`spent_tx`) == 1)
        self$`spent_tx` <- `spent_tx`
      }
      if (!missing(`time`)) {
        stopifnot(is.numeric(`time`), length(`time`) == 1)
        self$`time` <- `time`
      }
      if (!missing(`src_block_seq`)) {
        stopifnot(is.numeric(`src_block_seq`), length(`src_block_seq`) == 1)
        self$`src_block_seq` <- `src_block_seq`
      }
      if (!missing(`src_tx`)) {
        stopifnot(is.character(`src_tx`), length(`src_tx`) == 1)
        self$`src_tx` <- `src_tx`
      }
    },
    toJSON = function() {
      InlineResponse200Object <- list()
      if (!is.null(self$`hours`)) {
        InlineResponse200Object[['hours']] <- self$`hours`
      }
      if (!is.null(self$`coins`)) {
        InlineResponse200Object[['coins']] <- self$`coins`
      }
      if (!is.null(self$`uxid`)) {
        InlineResponse200Object[['uxid']] <- self$`uxid`
      }
      if (!is.null(self$`owner_address`)) {
        InlineResponse200Object[['owner_address']] <- self$`owner_address`
      }
      if (!is.null(self$`spent_block_seq`)) {
        InlineResponse200Object[['spent_block_seq']] <- self$`spent_block_seq`
      }
      if (!is.null(self$`spent_tx`)) {
        InlineResponse200Object[['spent_tx']] <- self$`spent_tx`
      }
      if (!is.null(self$`time`)) {
        InlineResponse200Object[['time']] <- self$`time`
      }
      if (!is.null(self$`src_block_seq`)) {
        InlineResponse200Object[['src_block_seq']] <- self$`src_block_seq`
      }
      if (!is.null(self$`src_tx`)) {
        InlineResponse200Object[['src_tx']] <- self$`src_tx`
      }

      InlineResponse200Object
    },
    fromJSON = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
      if (!is.null(InlineResponse200Object$`hours`)) {
        self$`hours` <- InlineResponse200Object$`hours`
      }
      if (!is.null(InlineResponse200Object$`coins`)) {
        self$`coins` <- InlineResponse200Object$`coins`
      }
      if (!is.null(InlineResponse200Object$`uxid`)) {
        self$`uxid` <- InlineResponse200Object$`uxid`
      }
      if (!is.null(InlineResponse200Object$`owner_address`)) {
        self$`owner_address` <- InlineResponse200Object$`owner_address`
      }
      if (!is.null(InlineResponse200Object$`spent_block_seq`)) {
        self$`spent_block_seq` <- InlineResponse200Object$`spent_block_seq`
      }
      if (!is.null(InlineResponse200Object$`spent_tx`)) {
        self$`spent_tx` <- InlineResponse200Object$`spent_tx`
      }
      if (!is.null(InlineResponse200Object$`time`)) {
        self$`time` <- InlineResponse200Object$`time`
      }
      if (!is.null(InlineResponse200Object$`src_block_seq`)) {
        self$`src_block_seq` <- InlineResponse200Object$`src_block_seq`
      }
      if (!is.null(InlineResponse200Object$`src_tx`)) {
        self$`src_tx` <- InlineResponse200Object$`src_tx`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hours": %d,
           "coins": %d,
           "uxid": %s,
           "owner_address": %s,
           "spent_block_seq": %d,
           "spent_tx": %s,
           "time": %d,
           "src_block_seq": %d,
           "src_tx": %s
        }',
        self$`hours`,
        self$`coins`,
        self$`uxid`,
        self$`owner_address`,
        self$`spent_block_seq`,
        self$`spent_tx`,
        self$`time`,
        self$`src_block_seq`,
        self$`src_tx`
      )
    },
    fromJSONString = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
      self$`hours` <- InlineResponse200Object$`hours`
      self$`coins` <- InlineResponse200Object$`coins`
      self$`uxid` <- InlineResponse200Object$`uxid`
      self$`owner_address` <- InlineResponse200Object$`owner_address`
      self$`spent_block_seq` <- InlineResponse200Object$`spent_block_seq`
      self$`spent_tx` <- InlineResponse200Object$`spent_tx`
      self$`time` <- InlineResponse200Object$`time`
      self$`src_block_seq` <- InlineResponse200Object$`src_block_seq`
      self$`src_tx` <- InlineResponse200Object$`src_tx`
    }
  )
)
